a = open("levels.txt", "r", encoding="utf-8")
b = a.readline()
c = a.readline()
d = a.readline()
e = a.readline()
f = a.readline()
print(b)
print(c)
print(d)
print(e)
print(f)
g = open("mistake.txt", "r", encoding="utf-8")
h = g.read()
print(h)
i = open("rules.txt", "r", encoding="utf-8")
j = i.read()
print(j)
